configuration:
  layout:
    - 0: {length: 0, upstream_neighbor: 2}
      2: {length: 10, upstream_neighbor: 3, adjacent_neighbor: 11}
      3: {length: 10, upstream_neighbor: 4}
      4: {length: 10, upstream_neighbor: 17, adjacent_neighbor: 7}
      17: {length: 0}
    - 1: {length: 0, upstream_neighbor: 5}
      5: {length: 10, upstream_neighbor: 6, adjacent_neighbor: 12}
      6: {length: 10, upstream_neighbor: 21, adjacent_neighbor: 4}
      21: {length: 10, upstream_neighbor: 8}
    - 7: {length: 10, upstream_neighbor: 8}
      8: {length: 10, upstream_neighbor: 9, adjacent_neighbor: 18}
      9: {length: 10, upstream_neighbor: 10, adjacent_neighbor: 19}
      10: {length: 10, upstream_neighbor: 20}
    - 11: {length: 10, upstream_neighbor: 12}
      12: {length: 10, upstream_neighbor: 13}
    - 13: {length: 10, upstream_neighbor: 14, adjacent_neighbor: 20}
      14: {length: 10, upstream_neighbor: 15, adjacent_neighbor: 19}
      15: {length: 10, upstream_neighbor: 16, adjacent_neighbor: 18}
      16: {length: 10, upstream_neighbor: 17}
    - 18: {length: 0}
      19: {length: 0}
      20: {length: 0}
  sources: [0, 1]
  sinks: [17, 18, 19, 20]

settings:
  bags_distr:
    sequence:
      - {bags_number: 200, delta: 20, sinks: [17, 18]}
      - {bags_number: 200, delta: 20}
      - {bags_number: 200, delta: 20, sinks: [17, 18]} 
      - {bags_number: 200, delta: 20}
      - {bags_number: 200, delta: 10} 
      - {bags_number: 400, delta: 10, simult_sources: 2}
      - {bags_number: 600, delta: 7, simult_sources: 2}
      - {bags_number: 800, delta: 4, simult_sources: 2}
      - {bags_number: 1100, delta: 3, simult_sources: 2}
      - {bags_number: 1200, delta: 2.5, simult_sources: 2}
      # - {bags_number: 800, delta: 2, simult_sources: 2}
      # - {bags_number: 666, delta: 4}
      # - {bags_number: 430, delta: 3}
  conveyor_env:
    speed: 1
    energy_consumption: 1
    sec_process_time: 2
  conveyor:
    stop_delay: 40
  router:
    simple_q:
      energy_reward_weight: 1
      learning_rate: 0.5
    dqn: &dqn
      energy_reward_weight: 1
      # energy_reward_weight: 0.8
      optimizer: 'rmsprop'
      scope: 'conveyor_test_ng'
      activation: 'relu'
      layers: [64, 64]
      additional_inputs:
        - tag: 'amatrix'
      batch_size: 1
      mem_capacity: 1
    dqn_oneout:
      <<: *dqn
    dqn_emb:
      <<: *dqn
      # energy_reward_weight: 0.2
      energy_reward_weight: 0.4
      additional_inputs: []
      # additional_inputs:
        # - tag: 'working'
          # dim: 1
      embedding:
        alg: 'lap'
        dim: 10

