configuration:
  layout:
    - 0: {length: 1, upstream_neighbor: 2}
      2: {length: 10, upstream_neighbor: 3, adjacent_neighbor: 11}
      3: {length: 10, upstream_neighbor: 4}
      4: {length: 10, upstream_neighbor: 17, adjacent_neighbor: 7}
      17: {length: 1}
    - 1: {length: 1, upstream_neighbor: 5}
      5: {length: 10, upstream_neighbor: 6, adjacent_neighbor: 12}
      6: {length: 10, upstream_neighbor: 21, adjacent_neighbor: 4}
      21: {length: 10, upstream_neighbor: 8}
    - 7: {length: 10, upstream_neighbor: 8}
      8: {length: 10, upstream_neighbor: 9, adjacent_neighbor: 18}
      9: {length: 10, upstream_neighbor: 10, adjacent_neighbor: 19}
      10: {length: 10, upstream_neighbor: 20}
    - 11: {length: 10, upstream_neighbor: 12}
      12: {length: 10, upstream_neighbor: 13}
    - 13: {length: 10, upstream_neighbor: 14, adjacent_neighbor: 20}
      14: {length: 10, upstream_neighbor: 15, adjacent_neighbor: 19}
      15: {length: 10, upstream_neighbor: 16, adjacent_neighbor: 18}
      16: {length: 10, upstream_neighbor: 17}
    - 18: {length: 1}
      19: {length: 1}
      20: {length: 1}
  sources: [0, 1]
  sinks: [17, 18, 19, 20]

settings:
  bags_distr:
    sequence:
      # - {pkg_number: 1000, delta: 10} 
      # - {bags_number: 2000, delta: 10}
      - {bags_number: 200, delta: 20, sinks: [17, 18]}
      - {bags_number: 200, delta: 20}
      - {bags_number: 200, delta: 20, sinks: [17, 18]} 
      - {bags_number: 200, delta: 20}
      - {bags_number: 200, delta: 20, sinks: [17, 18]} 
      - {bags_number: 200, delta: 20}
      - {bags_number: 200, delta: 20, sinks: [17, 18]} 
  conveyor_env:
    speed: 1
    energy_consumption: 1
    sec_process_time: 2
    # common_brain: True
  conveyor:
    stop_delay: 40
  router:
    energy_reward_weight: 0.5
    learning_rate: 0.5
    optimizer: 'rmsprop'
    scope: 'conveyor_test_ng'
    activation: 'relu'
    layers: [64, 64]
    # additional_inputs:
      # - tag: 'amatrix'
      # - tag: 'work_status'
    embedding:
      alg: 'lap'
      dim: 5
    batch_size: 1
    mem_capacity: 1
