configuration:
  sinks: [0]
  sources:
    0: {upstream_conv: 5}
  conveyors:
    0:
      length: 20
      upstream: {type: 'sink', idx: 0}
    1:
      length: 40
      upstream: {type: 'conveyor', idx: 2, pos: 0}
    2:
      length: 20
      upstream: {type: 'conveyor', idx: 3, pos: 0}
    3:
      length: 40
      upstream: {type: 'conveyor', idx: 4, pos: 0}
    4:
      length: 20
      upstream: {type: 'conveyor', idx: 1, pos: 0}
    5:
      length: 20
      upstream: {type: 'conveyor', idx: 1, pos: 20}
  diverters:
    0:
      conveyor: 3
      pos: 20
      upstream_conv: 0

settings:
  bags_distr:
    sequence:
      # - {pkg_number: 1000, delta: 10} 
      # - {bags_number: 2000, delta: 10}
      - {bags_number: 200, delta: 20, sinks: [0]}
      - {bags_number: 200, delta: 20}
      - {bags_number: 200, delta: 20, sinks: [0]} 
      - {bags_number: 200, delta: 20}
      - {bags_number: 200, delta: 20, sinks: [0]} 
      - {bags_number: 200, delta: 20}
      - {bags_number: 200, delta: 20, sinks: [0]} 
  conveyor_env:
    speed: 1
    energy_consumption: 1
  conveyor:
    stop_delay: 40
    slowdown_delay: 1
  router:
    simple_q:
      energy_reward_weight: 0.4 # * 0.0002
      learning_rate: 0.5
    dqn: &dqn
      energy_reward_weight: 1
      optimizer: 'rmsprop'
      scope: 'conveyor_test_ng'
      activation: 'relu'
      layers: [64, 64]
      additional_inputs:
        - tag: 'amatrix'
      batch_size: 1
      mem_capacity: 1
    dqn_oneout:
      <<: *dqn
    dqn_emb:
      <<: *dqn
      energy_reward_weight: 0.5
      additional_inputs: []
      embedding:
        alg: 'lap'
        dim: 5
