configuration:
  layout:
    - 0: {length: 0, upstream_neighbor: 2}
      2: {length: 10, upstream_neighbor: 3, adjacent_neighbor: 11}
      3: {length: 10, upstream_neighbor: 4}
      4: {length: 10, upstream_neighbor: 17, adjacent_neighbor: 7}
      17: {length: 0}
    - 1: {length: 0, upstream_neighbor: 5}
      5: {length: 10, upstream_neighbor: 6, adjacent_neighbor: 12}
      6: {length: 10, upstream_neighbor: 21, adjacent_neighbor: 4}
      21: {length: 10, upstream_neighbor: 8}
    - 7: {length: 10, upstream_neighbor: 8}
      8: {length: 10, upstream_neighbor: 9, adjacent_neighbor: 18}
      9: {length: 10, upstream_neighbor: 10, adjacent_neighbor: 19}
      10: {length: 10, upstream_neighbor: 20}
    - 11: {length: 10, upstream_neighbor: 12}
      12: {length: 10, upstream_neighbor: 13}
    - 13: {length: 10, upstream_neighbor: 14, adjacent_neighbor: 20}
      14: {length: 10, upstream_neighbor: 15, adjacent_neighbor: 19}
      15: {length: 10, upstream_neighbor: 16, adjacent_neighbor: 18}
      16: {length: 10, upstream_neighbor: 17}
    - 18: {length: 0}
      19: {length: 0}
      20: {length: 0}
  sources: [0, 1]
  sinks: [17, 18, 19, 20]

settings:
  bags_distr:
    sequence:
      - {bags_number: 200, delta: 20, sinks: [17, 18]}
      - {bags_number: 200, delta: 20}
      - {bags_number: 200, delta: 20, sinks: [17, 18]} 
      - {bags_number: 200, delta: 20}
      - {bags_number: 400, delta: 10} 
      - {bags_number: 440, delta: 9}
      - {bags_number: 500, delta: 8}
      - {bags_number: 570, delta: 7}
      - {bags_number: 666, delta: 6}
      # - {bags_number: 430, delta: 3}
  conveyor_env:
    speed: 1
    energy_consumption: 1
    sec_process_time: 10
  conveyor:
    stop_delay: 40
  router:
    energy_reward_weight: 1
    learning_rate: 0.5
    optimizer: 'rmsprop'
    scope: 'conveyor_test_ng'
    ff_activation: 'tanh'
    layers: [64, 64]
    additional_inputs:
      - tag: 'amatrix'
    pkg_states: False
    batch_size: 1
    mem_capacity: 1
    prioritized_xp: False
