network:
  - {u: 1, v: 2, latency: 10, bandwidth: 1024}
  - {u: 1, v: 3, latency: 10, bandwidth: 1024}
  - {u: 2, v: 7, latency: 10, bandwidth: 1024}
  - {u: 3, v: 7, latency: 10, bandwidth: 1024}
  - {u: 2, v: 9, latency: 10, bandwidth: 1024}
  - {u: 9, v: 10, latency: 10, bandwidth: 1024}
  - {u: 7, v: 8, latency: 10, bandwidth: 1024}
  - {u: 4, v: 5, latency: 10, bandwidth: 1024}
  - {u: 5, v: 6, latency: 10, bandwidth: 1024}
  - {u: 4, v: 8, latency: 10, bandwidth: 1024}
  - {u: 6, v: 8, latency: 10, bandwidth: 1024}
  - {u: 6, v: 10, latency: 10, bandwidth: 1024}

settings:
  pkg_distr:
    # - {pkg_number: 3000, delta: 10} 
    - {pkg_number: 500, delta: 20, sources: [1, 2, 3, 9], dests: [4, 5, 6, 10]}
  synchronizer:
    period: 10
    delta: 5
  logging:
    delta: 50
  router:
    learning_rate: 0.2
    pkg_process_delay: 5
 
